layout_spectrum: 0.4174142254050821
typography_spectrum: 0.8849967229180038
color:
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
  brandStrength: 0.565788208739832
  lightness: 0.2684094156138599
  saturation: 0.44551846757531166
  rhythmicContrast: 0.6347288668621331
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Groeneweg
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    id: 5e47f24d-9478-4267-b61b-0478c7463667
    type: content
favicon: null
title: Groeneweg
description: Motivation to Learn
purpose: []
