typography_spectrum: 0.23144
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6875
  lightness: 0.08381548314355314
  saturation: 0.3187532611191273
  rhythmicContrast: 0.3748316364362836
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50794
analytics:
  google: null
  facebook: null
  twitter: null
name: Groeneweg
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Groeneweg
purpose: []
